### ISSUE TITLE
Github Repository Removal Request

### ISSUE THREAD

**Issue by Cybersecurity-Specialist** [flutter-devs/flutter_Flipkart_UI_clone#2]
Hi,

​
My name is Gaspar Arizala from iZoologic and I am reaching out on behalf of Flipkart.
 
I am an authorized representative of Flipkart and it has come to their attention that a file associated with Flipkart has been uploaded to Github without prior authorization.

As the uploader of the content, we are requesting you to have the file you uploaded in Github to be removed as soon as possible as requested by our Client - Flipkart. 

Here is the link to the file uploaded on Github by your Github Account:

https://github.com/flutter-devs/flutter_Flipkart_UI_clone

We would appreciate your cooperation in removing the said repository as it is containing references of Flipkart.

Here are our contact details:

+442037342726 
Level 30, The Leadenhall Building 
122 Leadenhall Street, EC3V 4AB 
City of London, UNITED KINGDOM 
izoolabs@izoologic.com

I am providing this notice in good faith and with the reasonable belief that rights my company owns are being infringed. Under penalty of perjury, I certify that the information contained in the notification is both true and accurate, and I have the authority to act on behalf of the owner of the copyright(s) involved.

Should you have any concern please let us know.

Thanks and Regards,
Gaspar Arizala

**Comment by TheFlutterDevs** [comment]
Closing issue as there have been communications over email and the repo has been updated as per the discussions.
